### ISSUE TITLE
Partially unsynchronized access to annotations field in MoreUnitAnnotationModel

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#10]
While reading the sources of `MoreUnitAnnotationModel` in order to get [this pull request](https://github.com/MoreUnit/MoreUnit-Eclipse/pull/9) accepted, I stumbled upon several places where access to the `annotations` field is unsynchronized. Not sure if `MoreUnitAnnotationModel` needs to be thread-safe, but if thread-safety is required, the current implementation has some flaws.

For example `connect` and `disconnect` access the field unsynchronized. Also, `getAnnotationIterator` returns an iterator that acts on the raw list and will fail if used concurrently.

**Comment by gianasista** [comment]
Thank you for this hint, you are right, the flaws should be fixed.
