### ISSUE TITLE
Cannot install Mock Support 3.3.0 in Eclipse 2021-06

### ISSUE THREAD

**Issue by MahatmaFatalError** [MoreUnit/MoreUnit-Eclipse#118]
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: MoreUnit For Java: Mock Support 3.3.0 (org.moreunit.mock.feature.group 3.3.0)
  Missing requirement: MoreUnit Mocking Support 3.3.0 (org.moreunit.mock 3.3.0) requires 'osgi.bundle; org.jboss.tools.common.jaxb 3.6.100' but it could not be found
  Cannot satisfy dependency:
    From: MoreUnit For Java: Mock Support 3.3.0 (org.moreunit.mock.feature.group 3.3.0)
    To: org.eclipse.equinox.p2.iu; org.moreunit.mock [3.3.0,3.3.0]
```
![grafik](https://user-images.githubusercontent.com/776825/132092583-a3b6262f-8c9a-4465-84fb-70dd88831c0b.png)

Eclipse 2021-06 / STS 4.11.1.RELEASE

**Comment by apupier** [comment]
a workaround should consist in adding https://download.jboss.org/jbosstools/photon/stable/updates/ in the list of Update sites
https://github.com/MoreUnit/MoreUnit-Eclipse/blob/f7929f780c789cd519eed875e80495d6909c29b3/org.moreunit.build/eclipse-4.20.target#L19

**Comment by ckandirali** [comment]
At category.xml, repository-reference location value seems not correct (http://https://download.jboss.org/jbosstools/photon/stable/updates). http:// can be removed.

**Comment by apupier** [comment]
created https://github.com/MoreUnit/MoreUnit-Eclipse/pull/122

**Comment by Vankog** [comment]
Adding the update site to Eclipse did the trick for other plugins, too (Enhanced Class Decompiler).

Is the change to the category.xml already live? Because it seemingly did not work (yet) when installing via Marketplace.

**Comment by apupier** [comment]
the change is no live
