### ISSUE TITLE
In Preference page, the place for the tree to specify source folder should take more place

### ISSUE THREAD

**Issue by apupier** [MoreUnit/MoreUnit-Eclipse#12]
the text is cropped even for quite small project names although there is a lot of space to the right

![image](https://cloud.githubusercontent.com/assets/1105127/14541049/4bb6a11c-0288-11e6-9395-028fe3deabdc.png)

**Comment by apupier** [comment]
PR: https://github.com/MoreUnit/MoreUnit-Eclipse/pull/14

**Comment by rherrmann** [comment]
If I may add a little detail: I think the Add/Remote/Remap buttons should align with the top of the tree.

**Comment by apupier** [comment]
good suggestion, I implemented it. See https://github.com/MoreUnit/MoreUnit-Eclipse/pull/14

**Comment by apupier** [comment]
PR merged
