### ISSUE TITLE
Installation von MoreUnit from Marketplace failed / Eclipse 2021-09

### ISSUE THREAD

**Issue by thomaspkd** [MoreUnit/MoreUnit-Eclipse#125]
Installation from Marketplace failed with following error:

```
Unable to read repository at https://moreunit.github.io/eclipse-update-site/content.xml.
Connect to moreunit.github.io:443 [moreunit.github.io/185.199.108.153, moreunit.github.io/185.199.111.153, moreunit.github.io/185.199.109.153, moreunit.github.io/185.199.110.153] failed: Connect timed out
```

**Comment by akwala** [comment]
https://moreunit.github.io/eclipse-update-site/ gives 404 error.

**Comment by apupier** [comment]
The 404 is only because there is no index.html.

it seems to read the repository correctly from within Eclipse on my side:
![Screenshot from 2021-11-19 09-06-14](https://user-images.githubusercontent.com/1105127/142587587-b2391ab3-4a04-4e53-bc48-b89263bab98d.png)

**Comment by akwala** [comment]
> The 404 is only because there is no index.html.
> 
> it seems to read the repository correctly from within Eclipse on my side:

Thx. Yes, worked for me too.

**Comment by apupier** [comment]
I guess it was a temporary glitch from github. Please reopen if yopu still have the issue
