### ISSUE TITLE
Update Site for older Eclipse Versions (serving 3.2)

### ISSUE THREAD

**Issue by Vankog** [MoreUnit/MoreUnit-Eclipse#127]
Hi,

The current update site and Marketplace do not serve older Eclipse Versions.
However, we are currently stuck on e.g. 4.15 (due to some extensions).

Can you please provide an update site that still serves 3.2.x for older Eclipse versions?

**Comment by apupier** [comment]
note that last version of MoreUnit is not compatible with older Eclipse versions.

personally I do not have time to support older versions (barely have time to support latest). So you will need to come with the required Pull requests or host the update site yourself (or find someone or a company willing to pay for support of old versions)
