### ISSUE TITLE
Execute testmethod under cursor doesn't respect @ParameterizedTest

### ISSUE THREAD

**Issue by dstango** [MoreUnit/MoreUnit-Eclipse#140]
JUnit 5: When in a method annotated with @ParameterizedTest the usual shortcut to execute the current test method doesn't respect the annotation but instead executes all tests of the current class. Jumping to the method being tested works though.

Example:
	@ParameterizedTest
	@ValueSource(strings = {"2022-01-26T16:12:23.239Z", "2022-01-26T16:12:23.239", "2022-01-26", "2022-01-26T16:42:50.100Z"})
	void testToLocalDateTime_withValidTimeStrings_doesntThrowException(String s) throws Exception {
		assertDoesNotThrow(() -> DateConverter.toLocalDateTime(s));
	}

**Comment by dstango** [comment]
Looks like the relevant line of source code might be this: 

https://github.com/MoreUnit/MoreUnit-Eclipse/blob/e2441b49c0319f4bd462b1d61b711005580b842f/org.moreunit.plugin/src/org/moreunit/elements/MethodFacade.java#L26

in method

https://github.com/MoreUnit/MoreUnit-Eclipse/blob/e2441b49c0319f4bd462b1d61b711005580b842f/org.moreunit.plugin/src/org/moreunit/elements/MethodFacade.java#L22

I've never worked on an eclipse plugin before, so I rather point to the source code instead of creating a non-working pull request ;-) ...

**Comment by dstango** [comment]
This issue is closed as "completed" -- yet no PR is referenced. Is this just "closing all old issues"? I'm still interested in this functionality! And even extended configurability of supported annotations ...

**Comment by dstango** [comment]
@RoiSoleil being happy about the recent activity in the project, and appreciating your huge contributions I'd like to work on this issue and add more annotations like "ParameterizedTest" to the list of relevant annotations.

Question: Is it sufficient to clone and open the repository in a regular eclipse for plugin-development? Or do I need the "Eclipse IDE for Eclipse Committers" package?

**Comment by Bananeweizen** [comment]
> Question: Is it sufficient to clone and open the repository in a regular eclipse for plugin-development? Or do I need the "Eclipse IDE for Eclipse Committers" package?

Both are fine. The plugin-development part (PDE) also requires the Java tooling (JDT), and that is all you need. The "for committers" might have some more source code, documentation and helper plugins, which is why I take it for all plugin development (e.g. to not miss the description of plugin extension points and similar).

**Comment by dstango** [comment]
@Bananeweizen thanks. I ended up using PDE (after first trying the "regular" Java package), and I even found that recommended in the contributing file ... ;-)
