### ISSUE TITLE
Missing dependency 3.3.1 / update site incomplete

### ISSUE THREAD

**Issue by guw** [MoreUnit/MoreUnit-Eclipse#142]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/191472/153747247-e9b53c9e-afaf-4909-aa05-82cc99c8d7e4.png">

Trying to add it to a target platform raises the following issues. It looks like the bundle is references but not provided by the MoreUnit update site. At least I could not find it there.

> Diagnostic of the generation of the target platform.
Error occurred during resolution of 'https://moreunit.github.io/eclipse-update-site/'. The IU 'org.jboss.tools.common.jaxb' with range constraint '0.0.0' cannot be found.

If `org.jboss.tools.common.jaxb` is required by MoreUnit it should be included in the target platform.

**Comment by rainbow-six3** [comment]
Same issue here. Updatesite https://moreunit.github.io/eclipse-update-site/ returns 404

**Comment by guw** [comment]
@apupier Any chance you can provide an update that *includes* the jaxb dependency in the update site?

**Comment by apupier** [comment]
Unfortunately, for sure not in the 4 coming weeks

**Comment by apupier** [comment]
@guw I gave you rights to this repository. I think it should allow you to do it if you have time for it.

**Comment by apupier** [comment]
> Any chance you can provide an update that _includes_ the jaxb dependency in the update site?

I think this update site can be used https://devstudio.redhat.com/12/stable/updates/ (foudn from https://tools.jboss.org/downloads/devstudio/2021-09/12.21.3.GA.html#update_site )

**Comment by guw** [comment]
@apupier How can we release a staging/test update site with the changes from #157?

**Comment by apupier** [comment]
I do not think that there is something in place for a staging/test update site. If I remember well, you can only build the update locally as a zip. Then point to this locally built zip file and check manually this way

**Comment by apupier** [comment]
using the exploded local update site is working:
![image](https://user-images.githubusercontent.com/1105127/183038542-e6dcb920-e703-422a-ba79-868a76935971.png)

![image](https://user-images.githubusercontent.com/1105127/183038513-bd62a33f-fb8c-4876-aefc-edd396b9b80b.png)
![image](https://user-images.githubusercontent.com/1105127/183038623-d6ab654a-e0dd-4a8e-a16c-9e51ce5608f5.png)
![image](https://user-images.githubusercontent.com/1105127/183038799-0f396e4a-c023-40f9-b16d-c9522e58d51a.png)
