### ISSUE TITLE
Installation failed with requires 'osgi.bundle; org.jboss.tools.common.jaxb 3.6.100' but it could not be found

### ISSUE THREAD

**Issue by ahoehma** [MoreUnit/MoreUnit-Eclipse#160]
Cannot complete the install because one or more required items could not be found.
  Software being installed: MoreUnit For Java: Mock Support 3.3.1 (org.moreunit.mock.feature.group 3.3.1)
  Missing requirement: MoreUnit Mocking Support 3.3.1 (org.moreunit.mock 3.3.1) requires 'osgi.bundle; org.jboss.tools.common.jaxb 3.6.100' but it could not be found
  Cannot satisfy dependency:
    From: MoreUnit For Java: Mock Support 3.3.1 (org.moreunit.mock.feature.group 3.3.1)
    To: org.eclipse.equinox.p2.iu; org.moreunit.mock [3.3.1,3.3.1]

I already added https://download.jboss.org/jbosstools/photon/stable/updates/ but this doesnt help.

**Comment by Skillzore** [comment]
The same exact issue here. Running eclipse 2021-03 (4.19.0) if that matters. Also tried adding the JBoss update site, but no luck. Any ideas? Thought this was fixed based on #118.

**Comment by apupier** [comment]
this shoudl be fixed on main branch https://github.com/MoreUnit/MoreUnit-Eclipse/issues/142
I guess a new release is needed.
Is it right @guw ?

**Comment by guw** [comment]
That's correct. Is there any doc how to do it?

**Comment by guw** [comment]
That didn't work. I am probably missing a step about versioning.
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.moreunit.updatesite 3.4.0
[ERROR]   Missing requirement: org.moreunit.updatesite 3.4.0 requires 'org.eclipse.equinox.p2.iu; org.moreunit.dependencies.feature.group [3.4.0,3.4.1)' but it could not be found
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.moreunit:org.moreunit.updatesite:3.4.0 @ /Users/gwagenknecht/Development/eclipse/MoreUnit-Eclipse/org.moreunit.build/.release-build/org.moreunit.updatesite/pom.xml: See log for details -> [Help 1]
[ERROR] 
```

**Comment by dstango** [comment]
Did you take care of this prerequisite? 
ˋˋˋ
Check that MoreUnit:eclipse-update-site is cloned besides this repository
ˋˋˋ
I don't exactly know what 'besides' means here, ...

**Comment by guw** [comment]
Yes. It's failing *when* building the update site. I suspect there is something else I need to take care of around versioning.

**Comment by shneedle** [comment]
As a workaround the former JBoss Tools 4.23 update site can be added in Eclipse, so the missing dependency will be found: https://download.jboss.org/jbosstools/static/photon/stable/updates/core/4.23.0.Final/

**Comment by OlegAndreych** [comment]
FYI

Installation is still broken. Workaround is still working.
