### ISSUE TITLE
https://moreunit.github.io/eclipse-update-site/ not/no more available

### ISSUE THREAD

**Issue by reinhapa** [MoreUnit/MoreUnit-Eclipse#161]
The update site https://moreunit.github.io/eclipse-update-site/ as documented it not/no more available.

**Comment by apupier** [comment]
it is available for me:
![image](https://user-images.githubusercontent.com/1105127/189670520-a103a5ad-fd13-417b-a1b7-7a8e16399e27.png)

**Comment by m-kn** [comment]
I can confirm ... both!

When you open https://moreunit.github.io/eclipse-update-site/ in a browser, you get a 404 for some reason, while it used to be one of these https://de-jcup.github.io/update-site-eclipse-yaml-editor/update-site/ , i.e. a page explaining you're accessing a P2 update site and not a real page.

However, using https://moreunit.github.io/eclipse-update-site/ as a repo in a P2 task and exploring it works, so it should definitely be usable in eclipses install software wizard as well.

**Comment by reinhapa** [comment]
Got the error now, was on our company side :-(
