### ISSUE TITLE
MoreUnit Mock Support Integration Tests launch configuration not working on Windows

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#17]
The launch configuration specifies VM arguments like `-XstartOnFirstThread` and others that are specific to MacOS. 

On other platforms (namely Windows), these arguments are treated as errors and casue the VM to not start.

```
Unrecognized option: -XstartOnFirstThread
```

**Comment by apupier** [comment]
I fixed this point in https://github.com/MoreUnit/MoreUnit-Eclipse/pull/13 by providing a separated Launch Configuration

**Comment by rherrmann** [comment]
Fixed by merging PR #13.
