### ISSUE TITLE
Cannot install Mock Support 3.3.1 in Eclipse 2023-03

### ISSUE THREAD

**Issue by ayeseeem** [MoreUnit/MoreUnit-Eclipse#172]
(This looks very similar to the closed #118)

Details:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: MoreUnit For Java: Mock Support 3.3.1 (org.moreunit.mock.feature.group 3.3.1)
  Missing requirement: MoreUnit Mocking Support 3.3.1 (org.moreunit.mock 3.3.1) requires 'osgi.bundle; org.jboss.tools.common.jaxb 3.6.100' but it could not be found
  Cannot satisfy dependency:
    From: MoreUnit For Java: Mock Support 3.3.1 (org.moreunit.mock.feature.group 3.3.1)
    To: org.eclipse.equinox.p2.iu; org.moreunit.mock [3.3.1,3.3.1]
```

**Comment by mmaenz** [comment]
Hi

same problem here.
<img width="928" alt="image" src="https://github.com/MoreUnit/MoreUnit-Eclipse/assets/22559887/e7ab46b6-ad4b-4070-ab26-a46676e433af">

Is there any solution to this problem yet?

Thanks!

**Comment by ayeseeem** [comment]
Why was this closed? I've just checked, and it still fails to install.
Even if it has been fixed in the code, it won't actually be fixed until a new release is created and available on Eclipse Marketplace.

**Comment by ayeseeem** [comment]
This is excellent news, thank you :-)
