### ISSUE TITLE
removing the target files broke local development

### ISSUE THREAD

**Issue by Bananeweizen** [MoreUnit/MoreUnit-Eclipse#177]
I appreciate the recent cleaning up. But 5788d7dbe80ed42f2ed5e798312bc257949820a0 was a bit too much, specifically the removal of target files and the reliance on the download/latest URL in the maven build. That brings the following problems:
* The code has hundreds of compile errors in the IDE because there is no target platform that contains all dependencies (e.g. SWTBot etc.). Unless you install the dependencies into the IDE, which is definitely not the recommended way.
* MoreUnit will break, when being installed into older version of Eclipse, because compiling against the latest version from the servers will lead to using APIs not existing in older versions, or simply having minimum versions in require bundles/import packages which are impossible in older Eclipse versions.
* The build will break without any code changes, because the "latest" URL has new content every 3 months (e.g. exactly today it suddenly serves 2023-12 instead of -09 from that URL).

If agreed I'd like to re-add local target platform definitions. I'm fine with basing them on the current release (4.30) instead of the previous 4.24, if you want to get rid of old versions, but at least those files are needed for developing.  If you feel like .target files are hard to maintain (which is true), there is a simple DSL that can allows listing features, plugins and even plain maven dependencies and to generate a .target from that: https://github.com/ssi-schaefer/lcdsl. I'd happily provide a PR to include that.

**Comment by RoiSoleil** [comment]
Can you provide a PR with a target platform for the last Eclipse version ?

**Comment by Bananeweizen** [comment]
I would like to create a target platform for Eclipse 4.25 instead of latest (4.30). Reason is that 4.25 is the minimum Eclipse version running on Java 17, which is what the moreunit bundles require: https://wiki.eclipse.org/Eclipse/Installation
Does that sound okay for you? I know it compiles without problems, since I have restored the 4.24 target from git history locally as a workaround.

**Comment by Bananeweizen** [comment]
A target platform is what ensures the compatibility to a minimum version of Eclipse (more specifically to the set of features/bundles contained in the target platform). If you would always build and test against the latest target platform, then you would give up compatibility to older versions every 3 months when a new release comes out. And that's where so many bug reports in marketplace come from, because many people do not upgrade their base Eclipse installation regularly.
We can have an _additional_ target platform for the latest version. During development you can then choose between them, if you like testing against the more modern Eclipse more than testing against the older one. But the CI system should generally use the older one to make sure outside users can install in their old version.
