### ISSUE TITLE
No ShortcutStrategy to run SWTBot tests on Windows

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#18]
SWTBot tests fail because there is no matching key shortcut strategy for Windows. It would probably be sufficient to reuse the `LinuxShortcutStrategy`.

BTW, even though there is an `org.moreunit.swtbot.test.launch` file in `org.moreunit.swtbot.test`, I wasn't able to locate the corresponding launch configuration in the launch dialog.

**Comment by apupier** [comment]
I also fixed this point in #13 by providing a "Windows and Linux" ShortcutStrategy

**Comment by apupier** [comment]
PR merged

**Comment by rherrmann** [comment]
Fixed by merging PR #13.
