### ISSUE TITLE
Test failures?

### ISSUE THREAD

**Issue by Bananeweizen** [MoreUnit/MoreUnit-Eclipse#192]
Does anyone have an idea what the test failures mean? I thought that this one would be related to access rights in the workflow declaration, but that seems wrong:
![grafik](https://github.com/MoreUnit/MoreUnit-Eclipse/assets/406876/8f583416-2696-4304-bfc7-a18647ee8974)

I find it quite confusing that some builds of the past were green although I cannot see changes that would fit to the toggling between green and red. Or should we just disable the PreferencesTest that has failing tests immediately before the above message in the log?

**Comment by RoiSoleil** [comment]
This should be fixed with this change in https://github.com/MoreUnit/MoreUnit-Eclipse/pull/218/commits/380e29700bcf627c43e57a76e21606e752d4f803
