### ISSUE TITLE
MoreUnit is not available for Eclipse Neon

### ISSUE THREAD

**Issue by jabby** [MoreUnit/MoreUnit-Eclipse#2]
Today, I tried to install MoreUnit in Eclipse Neon M4. It seems that the plugin is not available for the next version of Eclipse IDE. 

You can download the milestone of Eclipse Neon here : https://www.eclipse.org/downloads/index-developer.php

**Comment by ndemengel** [comment]
Hi Jabby,

Sorry for the late answer and thanks for your report. I will give it a try.

**Comment by ndemengel** [comment]
Hi Jabby,

I just try again with the latest version of Neon (M5), then installing MoreUnit from the Marketplace, and it worked fine. Can you confirm that it works for you too?

**Comment by jabby** [comment]
It works. Thanks. I close this issue.
