### ISSUE TITLE
Renamed feature breaks update

### ISSUE THREAD

**Issue by Bananeweizen** [MoreUnit/MoreUnit-Eclipse#202]
Up to 3.3.1 the moreunit main feature had the ID "org.moreunit". Since 3.3.2 it's called "org.moreunit.feature" instead (and the same renaming happened for the other 2 features). See feature.xml for the ID.

The problem with the rename is that it breaks updates of existing installations, because the P2 update manager will look for newer versions of the old name. I experienced that today at work when I added the new update site to our Oomph setups and no updates were found.

I can see fa780676e8412a4dc0eea777aba694f776d63dd6 as the root cause, but I'm not sure what kind of collision you experienced. In my imagination, there should not be a problem from having a plugin and feature with same ID. p2 will handle them as different installable units. What problem did you experience, @RoiSoleil ?

**Comment by RoiSoleil** [comment]
Having a identical id for plugin and feature break the flattening of P2 repository to host the update site using github release. I don't want to revert that change because this is way more easy to provide flatten P2 automatically.
