### ISSUE TITLE
Why does MoreUnit have commands for running tests?

### ISSUE THREAD

**Issue by Bananeweizen** [MoreUnit/MoreUnit-Eclipse#209]
Looking at the recently merged PR which added more key bindings, I must ask the question: Why does MoreUnit have commands for running tests? I wasn't aware of them before. JDT, PDE, SWTBot etc. all bring their own commands and key bindings already. E.g. Alt-Shift-X followed by one of T(est), P(lugin test), S(wtbot test) and similar Alt-Shift-D for debugging the same. These commands are context aware, e.g. they can be launched on methods, tests, packages, projects, etc.

Why does MoreUnit need additional commands? What am I missing? In fact, for all non-plain unit tests (that is plugin test, swtbot tests etc.) the MoreUnit commands cannot work correctly based on the short experiement I did, since they cannot know that a plugin test needs to be launched as such etc.

**Comment by dstango** [comment]
The standard JDT commands require me to be on the method name, if I want to execute a single test method. The MoreUnit commands for individual tests can be invoked wherever I am with the cursor in a test method.

Or - when the cursor is in the test - I can choose to run all tests in the class with the other shortcut.

But you're right: they are only suitable for plain unit tests.

**Comment by Bananeweizen** [comment]
I'll check if I can find a way to convert the MoreUnit commands to delegates. I.e. if the class to be launched contains a freely defined String like "SWTBot", delegate to the SWTBot launch, otherwise if it contains "Workspace" or similar, delegate to Plugin tests, etc.
