### ISSUE TITLE
Support jumping/creating Groovy Spock Tests

### ISSUE THREAD

**Issue by NaanProphet** [MoreUnit/MoreUnit-Eclipse#21]
It would be really cool if the Ctrl+J keyboard shortcut could also be used to create Spock-based tests for production Java code.

Would anyone know if this is theoretically possible? If so i can attempt adding this feature

**Comment by gianasista** [comment]
As we don't have much time to add new features to MoreUnit at the moment we would be happy to see contributions.

**Comment by NaanProphet** [comment]
Great, i'll try my hand at contributing this then. Just successfully compiled a local version with Maven and will begin tweaking. :)

**Comment by konfri** [comment]
Hey,
I just tried it and "jumping" works for me after setting the test file patter to _${srcFile}(Test|Spec)_. The run tests command also works nicely. 

Only the "creation" just dumps an junit method frame into a  spoc/groovy file 😃 

Anyway, thank for the great plugin. It really makes much more fun while working with eclipse and tests 👍
