### ISSUE TITLE
Jump To Test should not ask for method name

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#24]
This is a copy of [feature request 85 @ sourceforge](https://sourceforge.net/p/moreunit/feature-requests/85/)

The "Jump To Text/Source" command (Ctrl+J) often shows a popup windows with a list to "destination methods" to jump to. As in my case the cursor is almost always at the right position in the respective source/test file editor, the extra popup is disruptive.

There are two options in project properties > MoreUnit > Java > Other
- _Enable test method search "my call"_
- _Enable test method search "my name"_
  that seem to control how "destination method" candidates are determined.However, it is currently not possible to uncheck both options.

I suggest to allow to uncheck both options. Leaving the default and all as it is, this would not break backward compatibility.

If both test method search options are unchecked, the _Junp To_ command would merely switch editors without changing the cursor location in the destination editor. When there is no editor open yet, the cursor would end up at the top of the file.I would leave that as it is for now and see if a better strategy is neccessary and feasible.

If there are no objectsions, I'll try to come up with a pull request.

**Comment by ndemengel** [comment]
It could do the trick, but the "test method search" feature is not only used to "jump", therefore we should first ensure that it won't deactivate other desirable behaviors.

**Comment by rherrmann** [comment]
If you agree, I would upload a (draft) pull request that you could check for possible unwanted side effects.

**Comment by ndemengel** [comment]
I quickly scanned the code, and there are two other impacted areas:

- the "Run test" action which wouldn't run a single test method anymore (not a real problem in my opinion)
- the MethodTreeContentProvider that wouldn't display anything. That said, we could force the search in this class, regardless of the user preferences.

Therefore we can either accept that or create yet another option that wouldn't cause conflicts. @gianasista: any preference?
