### ISSUE TITLE
EclipseResourcesTest failing non-deterministically

### ISSUE THREAD

**Issue by NaanProphet** [MoreUnit/MoreUnit-Eclipse#29]
Hello all,

I'm trying to run all tests on the latest, vanilla code using `mvn clean install.` Sometimes thought (it would seem every other time) the following test fails:

```
Tests in error:
  resource_containers_should_complain_when_requested_file_path_is_used_by_a_non_
existing_folder(org.moreunit.core.resources.EclipseResourcesTest): Problems enco
untered while deleting resources.

Tests run: 304, Failures: 0, Errors: 1, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MoreUnit Parent .................................... SUCCESS [  0.451 s]
[INFO] org.moreunit.core .................................. SUCCESS [  8.958 s]
[INFO] org.moreunit ....................................... SUCCESS [  7.383 s]
[INFO] org.moreunit.test.dependencies ..................... SUCCESS [ 36.897 s]
[INFO] org.moreunit.core.test ............................. FAILURE [ 51.412 s]
[INFO] org.moreunit.light.feature ......................... SKIPPED
[INFO] org.moreunit.test .................................. SKIPPED
[INFO] org.moreunit.feature ............................... SKIPPED
[INFO] org.moreunit.mock .................................. SKIPPED
[INFO] org.moreunit.mock.test ............................. SKIPPED
[INFO] org.moreunit.mock.it ............................... SKIPPED
[INFO] org.moreunit.mock.feature .......................... SKIPPED
[INFO] org.moreunit.swtbot.test ........................... SKIPPED
[INFO] org.moreunit.updatesite ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

Would anyone know what could be causing the issue? The tests are running on Windows using Eclipse Mars.

**Comment by ndemengel** [comment]
Hi NaanProphet,

I personally never observed a failure of this test. Could you share your detailed test result (in target/surefire-reports), maybe they will contain some indication.

Thanks!

**Comment by NaanProphet** [comment]
Sure thing, good idea!

Just ran it again this morning and attaching the EclipseResourcesTest failure from the surefire-report folder. This time, though, it failed for `resource_containers_should_complain_when_requested_file_path_is_used_by_an_existing_folder` and `workspace_should_complain_when_requested_folder_path_has_only_one_segment`

[TEST-org.moreunit.core.resources.EclipseResourcesTest.xml.txt](https://github.com/MoreUnit/MoreUnit-Eclipse/files/259611/TEST-org.moreunit.core.resources.EclipseResourcesTest.xml.txt)

Perhaps there's some OS system difference between deleting folders that are currently in use?
