### ISSUE TITLE
MoreUnit breaks Eclipse Java CallHierarchy-View

### ISSUE THREAD

**Issue by brychcy** [MoreUnit/MoreUnit-Eclipse#3]
With symptoms like described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=487067 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=484119, MoreUnit breaks
the Java Call Hierarchy View.

**Comment by brychcy** [comment]
See pull request.

**Comment by ndemengel** [comment]
Hi brychcy,

Thanks, that would indeed restrain the problem to concurrent searches.

I will include the change soon, and deactivate the default scan for test methods to further limit the issue to "jumps" between classes (see https://sourceforge.net/p/moreunit/bugs/135/).
