### ISSUE TITLE
Release 3.1.1 version

### ISSUE THREAD

**Issue by apupier** [MoreUnit/MoreUnit-Eclipse#30]
Eclipse Neon has been released. What do you think to make a MoreUnit release? Is the process complicated?

I provided the PR to update to stable Neon repository for the Target Platform.
Not included the Oxygen (4.7) next TP as the Integration build Update sites seems to not be available yet.

**Comment by gianasista** [comment]
Sorry for the late answer, Nicolas has written a shell script to release a new version.
It is in org.moreunit.build (release.sh).
As he did the last releases of MoreUnit he would be the best person to help out.

You have created a pull request. You should have developer access to the repo too, have you checked if it works?

**Comment by apupier** [comment]
All tests ran OK yes :-)

**Comment by ndemengel** [comment]
Hi Aurélien,

Oops, sorry for not having answered. Indeed, there is a script encapsulating the various tasks required for a proper deployment (maven + upload to the update site, hosted on our SourceForge FTP space). The only thing not done by the script is the upload of an archive to our SourceForge "files" section. We still perform this step for users that don't want or can use the update site, but maybe we could store those files as Github Releases so we can automate it.

Anyway, for the upload to the update site to work, you need to set your SourceForge credentials as explained in org.moreunit.build/readme.txt. So first thing first, do you have a SourceForge account so that we can give you an access to the FTP server?

**Comment by apupier** [comment]
created an account apupier

**Comment by ndemengel** [comment]
You're now a developer on the project. You should provide your SSH public key here https://sourceforge.net/auth/shell_services and try to connect to the FTP server via a FTP client (to update the website, this isn't automated either), and via SSH (to be confident that rsync will work).

Example of a successful connection:
```sh
» ssh ndemengel,moreunit@web.sourceforge.net                                                                                          
PTY allocation request failed on channel 0

Welcome!

This is a restricted Shell Account.
You can only copy files to/from here.

Connection to web.sourceforge.net closed.
```

**Comment by apupier** [comment]
connection through SSH and FTP ok :-)

**Comment by ndemengel** [comment]
Great! Feel free to release a version :-)

The process is as follows:

- edit content of \<article id="releasenotes"\> in homepage/index.html and commit/push
- run release.sh
- manually upload org.moreunit.build/.release-build/org.moreunit.updatesite/target/org.moreunit-VERSION.zip to https://sourceforge.net/projects/moreunit/files/moreunit/ (first create a folder as for the other downloads)
- ensure the file is the default download for all platforms, via its parameters
![upload1](https://cloud.githubusercontent.com/assets/468872/16521815/c7b17924-3f99-11e6-9b75-2c55af2087a0.png)
![upload2](https://cloud.githubusercontent.com/assets/468872/16521816/c7b55d5a-3f99-11e6-9755-20ca97c29c52.png)
- manually upload homepage/index.html to apupier,moreunit@web.sourceforge.net:/home/groups/m/mo/moreunit/htdocs/, using a FTP client

**Comment by apupier** [comment]
I updated the release note.
I'm not able to make the script working on my Windows Machine (I tried with git Bash and cygwin)

**Comment by ndemengel** [comment]
OK, I will give it a try tomorrow (I can't right now). What's the error with the script?

**Comment by apupier** [comment]
On git bash --> missing rsync command
On cygwin --> seems lost in paths and cannot find/ create .release-build
folder

On Friday, 1 July 2016, Nicolas Demengel <notifications@github.com> wrote:

> OK, I will give it a try tomorrow (I can't right now). What's the error
> with the script?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MoreUnit/MoreUnit-Eclipse/issues/30#issuecomment-229996203>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABDc5xuM_u3r5KBmk0AGvG81UHMf1NN0ks5qRUZ-gaJpZM4I9lIC>
> .
>


-- 
Aurelien Pupier
Senior Software Engineer in JBoss Fuse Tooling team
@apupier

**Comment by ndemengel** [comment]
Version 3.1.1 has been released. We should have a look at the script to make it work for everyone.
Also, I still have failing SWTBot tests.
Finally, it should be possible to remove all human steps now: https://sourceforge.net/p/forge/documentation/Release%20Files%20for%20Download/#scp

**Comment by ndemengel** [comment]
Also, the Eclipse Marketplace still displays "3.0.4". @gianasista: do you know where/how to change it? I suppose we made the version part of the name...

**Comment by apupier** [comment]
Thank you @ndemengel for the release

On Eclipse MarketPlace, the "Date updated" is still: 
Mon, 2016-02-22 14:14

Teh Version Number has to be provided manually in Edit--> Solution Version-> Version number section of Markeptplace.
Can you give the right access? i can update it.
(you can add it throuhgh Edit --> Additional editors , my id is apupier)

**Comment by ndemengel** [comment]
I don't have any access either so I will let @gianasista fix that.
Le 2 juil. 2016 9:26 AM, "Aurélien Pupier" <notifications@github.com> a
écrit :

**Comment by gianasista** [comment]
I have updated the version number on marketplace.
The project is connected to my private login and I have not seen anything that I can grant access to others (only on a quick glimpse with Til in my arms ;-) )

**Comment by gianasista** [comment]
@apupier Sorry my mistake, you are added as additional editor now.

**Comment by apupier** [comment]
This version has been successfully released!

thank you :-)
