### ISSUE TITLE
Jump to test/source - option to load in other editor pane

### ISSUE THREAD

**Issue by philipa** [MoreUnit/MoreUnit-Eclipse#32]
A feature request.

My preferred way of working is to have a unit test in one editor pane and the class under test in another, so I can see both at once. It would be good if I could configure MoreUnit to understand this, so Ctrl-J used the other editor pane to open the file rather than creating a new tab in the current pane.

**Comment by dstango** [comment]
I like to work in a similar way, yet I wonder if this could best be handled in MoreUnit or in a plugin like HandySplit (https://github.com/akikhtenko/HandySplit).

However done: we would probably need some preferences like 
* Open test file in (left|upper|right|lower) editor pane (and CUT in opposite pane)
  * only if editor pane available, and file already not opened,
  * only if editor pane available - move file to corresponding pane if in different pane,
  * always - create new editor pane if not available and move file there.
