### ISSUE TITLE
Suggested tweak for integration tests: make ${srcFile}(Test|IT) the default test name pattern

### ISSUE THREAD

**Issue by philsurette** [MoreUnit/MoreUnit-Eclipse#37]
Just like `${srcFile}Test` is the default naming convention for unit tests, `${srcFile}IT` is arguably the default pattern for integration tests - for instance, this is what the maven failsafe plugin uses by default: see http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html. The other common approach for integration tests is to use an separate folder for integration tests. 

In order to improve usability of MoreUnit out of the box, I suggest baking this into the default pattern that moreunit uses. This amounts to replacing `${srcFile}Test` with `${srcFile}(Test|IT)` as the default pattern. This has the additional benefit of making it obvious to users how to add additional patterns.

Thanks for the great plugin!

**Comment by dstango** [comment]
@RoiSoleil I agree with @philsurette's suggestion, would like to work on a PR and ask for reopening the issue.
