### ISSUE TITLE
"import" be removed

### ISSUE THREAD

**Issue by yufeng0528** [MoreUnit/MoreUnit-Eclipse#38]
I select "JUnit 4", and select some method,but the result file has not the "org.junit.Test";

[code]
if(isJUnit4())
        {
            imports.addStaticImport("org.junit.Assert", "*", false);
            // $NON-NLS-1$ //$NON-NLS-2$
            imports.addImport("org.junit.Test");
        }
[/code]
while the import is missing

**Comment by ndemengel** [comment]
Hi yufeng0528,

Is your project configured with JUnit4 as one of its dependencies?

**Comment by apupier** [comment]
@yufeng0528 feel free to reopen the issue if you have more information
