### ISSUE TITLE
When installing, org.eclipse.oomph.setup.core.feature.group could not be found

### ISSUE THREAD

**Issue by haynesgt** [MoreUnit/MoreUnit-Eclipse#39]
Product | Version
------------ | -------------
Eclipse | Version: Neon Release (4.6.0) Build id: 20160613-1800
MoreUnit | 3.11

## Problem

When installing MoreUnit from the Eclipse Marketplace, the installer fails and displays this message:

> Cannot complete the install because one or more required items could not be found.
>   Software currently installed: Oomph Setup 1.5.0.v20160818-1158 (org.eclipse.oomph.setup.feature.group 1.5.0.v20160818-1158)
>   Missing requirement: Oomph Setup 1.5.0.v20160818-1158 (org.eclipse.oomph.setup.feature.group 1.5.0.v20160818-1158) requires 'org.eclipse.oomph.setup.core.feature.group [1.5.0.v20160818-1158]' but it could not be found

**Comment by ndemengel** [comment]
Hi haynesgt,

Sorry for the very late answer. As far I can tell, your problem is not related to MoreUnit. Just to be sure, I just installed a fresh version of Eclipse Neon with MoreUnit, and everything ran fine.

**Comment by apupier** [comment]
@haynesgt seems that the issue was not related to MoreUnit so i close it. If you have more information please reopen it.
