### ISSUE TITLE
[MoreUnit Light] Sourcefile and testfile should be allowed to have different file extensions. 

### ISSUE THREAD

**Issue by niecore** [MoreUnit/MoreUnit-Eclipse#42]
When you are doing unittests for a c based project which uses a c++ testing framework your unit test will have a different file extension then the source file.

This should be configurable for each language.

**Comment by niecore** [comment]
Any feedback on this request?

**Comment by apupier** [comment]
@niecore hello, this idea seems interesting. i don't think that any maintainers will have time to implement it but if you are providing a Pull Request, there are good chance that it will be reviewed (and hopefully merged).

**Comment by niecore** [comment]
@apupier Thanks for your feedback. 

I opened the pullrequest https://github.com/MoreUnit/MoreUnit-Eclipse/pull/44 which includes this feature.
