### ISSUE TITLE
Add an option to let Ctrl + R run tests in debug mode

### ISSUE THREAD

**Issue by jpchristen** [MoreUnit/MoreUnit-Eclipse#43]
Currently Ctrl + R runs tests in run mode.

As I usually use the debug mode in order to get more information when a test doesn't work properly, it would be nice if there is a possibility to change Ctrl + R to start tests in debug mode.

**Comment by apupier** [comment]
Seems a nice request.
We have 2 possibilities to implement this kind of features:
- provide a preference to change run/debug for Ctrl+R
- provide another shortcut for debug, what about Ctrl+Alt+R?

Ctrl+Shift+ R is already used for "Open resource", i fear some collision.
Ctrl+Alt+R is already used for "Run" in "Servers view" so should have no collision

**Comment by jpchristen** [comment]
Both solutions would be perfectly fine for me. 
But is there actually a case where you don't want to start in debug mode? Only if you got a lot of breakpoints you don't want to step into and you are not willed to delete them. As I think that debug mode is usually the better way to run a test, I would prefer the first solution, as the shortcut is kept simple and in most situations you should be fine with one mode, so I guess you don't have to switch often.

**Comment by blackfoxoh** [comment]
I would prefer a second shortcut. If someone doesn't want to use it or change it the eclipse keys-preferences let's everyone choose his favourite behaviour...

**Comment by dstango** [comment]
I'd go for a second shortcut, too. Or even an unassigned command, with no predefined key-binding, so one can configure it individually.

**Comment by dstango** [comment]
I find this issue still relevant ...
