### ISSUE TITLE
Support JUnit tests defined in an eclipse fragment

### ISSUE THREAD

**Issue by apupier** [MoreUnit/MoreUnit-Eclipse#5]
One of the way to write unit tests for Eclipse plugin is to provide a fragment.
It would be nice to support it in order to have the link between the test class and the test under class.

**Comment by ndemengel** [comment]
Actually, it is supported :-)

It has to be configured on a per-project basis, please refer to http://moreunit.sourceforge.net/#doc-projectproperties
