### ISSUE TITLE
Support JUnit 5

### ISSUE THREAD

**Issue by apupier** [MoreUnit/MoreUnit-Eclipse#51]
Junit  will be released soon. Will be nice to test what need to be done to be compatible.

**Comment by earcam** [comment]
Just to add; integration is built-in with Oxygen.2 Release (4.7.2)

And 5.1.0 released a few days ago - [maven central](http://search.maven.org/#search%7Cga%7C1%7C(g%3A%22org.junit.jupiter%22%20OR%20g%3A%22org.junit.vintage%22)%20AND%20v%3A%225.1.0%22)

**Comment by apupier** [comment]
was done a while ago
