### ISSUE TITLE
Unable to install MoreUnit from new update site

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#54]
I am unable to install MoreUnit from the new update site. After entering `https://github.com/MoreUnit/eclipse-update-site` in the _Install Software_ dialog, an error message is shown:

![image](https://user-images.githubusercontent.com/607182/30921937-01ede726-a3a8-11e7-84f5-e4ceb7163d19.png)

**Comment by ndemengel** [comment]
Hi Rüdiger,

Thanks for the report! We accidentally put the link to the Github repo instead of the exposed website. It should be fixed now.

**Comment by rherrmann** [comment]
Thank you very much, Nicolas, the updated link works!
