### ISSUE TITLE
Update site seems not to work

### ISSUE THREAD

**Issue by frankbenoit** [MoreUnit/MoreUnit-Eclipse#55]
There are 2 candidates, at sourceforge and from github.  
Neither works for me.  
The marketplace link seems to be broken as well.

**Comment by rherrmann** [comment]
I just successfully used the update site from https://moreunit.github.io/MoreUnit-Eclipse/#download

Note that you need to **uninstall** MoreUnit first if you obtained the currently installed version from the Sourceforge update site at http://moreunit.sourceforge.net/org.moreunit.updatesite/ 

Can you post the exact URLs that you tried?

**Comment by frankbenoit** [comment]
@rherrmann thanks for the hint..  
Meanwhile with a fresh Eclipse 4.7.1 I retried and it worked.
I used: https://moreunit.github.io/eclipse-update-site/

**Comment by Catscratch** [comment]
Have to reopen this. Can you move the market place update site to github? Installing through marketplace isn't working anymore because sourceforge update site is down and looks like it will never come up again.

**Comment by gianasista** [comment]
I have changed the update site on marketplace to the github site.
