### ISSUE TITLE
Support for file extension pattern mapping

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [MoreUnit/MoreUnit-Eclipse#59]
1. current hard coded assumption is that main vs test differ in file name, not file extension
```
Some.java -> SomeTest.java
```
2. there are languages, i.e. TCL, which map via changing of file extension
```
some.tcl -> some.test
```

**Comment by AxelBerres** [comment]
We use strongly XTend and it would be nice, if more unit supports the correct decoration for the Class under test. XTend generates Java Classes but the code is original written in Xtend. Therefore the XTend class shall be decorated.
