### ISSUE TITLE
Layout of source folder selection dialog broken

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#6]
The layout of the source folder selection dialog that is used in the project-specific properties is broken. 
See the screenshoft for an example:
![screenshot](https://cloud.githubusercontent.com/assets/607182/14411409/9917f800-ff47-11e5-91f2-03ad0cb5ac3a.png)

Note that the tree is cut off at the bottom by default and does not adjust its size when the dialog is resized.

**Comment by apupier** [comment]
PR https://github.com/MoreUnit/MoreUnit-Eclipse/pull/15

**Comment by rherrmann** [comment]
PR #15 was merged.
