### ISSUE TITLE
MoreUnit-mock plugin fails to load under Java 11

### ISSUE THREAD

**Issue by helospark** [MoreUnit/MoreUnit-Eclipse#63]
## Background
I'm getting the following exceptions when trying to use MoreUnit plugin under Java 11 and Eclipse Photon:
```
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException cannot be found by org.moreunit.mock_3.1.1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
       ....
```
And the mock generation page is not showing up in the wizard, neither any mock is generated.
Rest of the plugin seems to work correctly.

This happens because JavaEE modules have been removed in Java 11:
http://openjdk.java.net/jeps/320
https://jaxenter.com/jdk-11-java-ee-modules-140674.html

Causing ClassNotFoundException, due to references to these in the plugin.

## Solution
Since mock module is a [direct user](https://github.com/MoreUnit/MoreUnit-Eclipse/blob/8e901e9b41472eb716b5f6ab84b28e43d03af0b0/org.moreunit.mock/src/org/moreunit/mock/templates/XmlTemplateDefinitionReader.java#L9) of these modules, it should add the correct javax.xml.* dependency to it, and some implementation for them.
Alternatively parsing XMLs could be done in non-JavaEE ways to avoid pulling in such a large depedencies.

## Notes
Usually I have used the [Maven artifacts](https://mvnrepository.com/artifact/javax.xml) to resolve issues like this, but as I see this project uses only Eclipse plugin-dependencies, not sure, if there is one that should be used in this case.

**Comment by mwensveen-nl** [comment]
Solving this bug is now essential to be able to run the plugin in the commont 2020-09 release. From this release java 11 will be mandatory.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=564035

**Comment by mwerlitz** [comment]
Found a simple solution to bundle required JAXB libs with the plugin.
Might not be the best solution (I'm not a eclipse plugin developer), but works for the moment.

Building my patched version (https://github.com/mwerlitz/MoreUnit-Eclipse/tree/63-java11runtime-support) with a JDK8 allows me to run the plugin with 2020-12 on a JDK11.

If some is interrested you will find the update site as a zip at https://github.com/mwerlitz/MoreUnit-Eclipse/releases/tag/v3.2.2

**Comment by wprogLK** [comment]
> Found a simple solution to bundle required JAXB libs with the plugin.
> Might not be the best solution (I'm not a eclipse plugin developer), but works for the moment.
> 
> Building my patched version (https://github.com/mwerlitz/MoreUnit-Eclipse/tree/63-java11runtime-support) with a JDK8 allows me to run the plugin with 2020-12 on a JDK11.
> 
> If some is interrested you will find the update site as a zip at https://github.com/mwerlitz/MoreUnit-Eclipse/releases/tag/v3.2.2

saved me today. thanks a lot @mwerlitz.
If somebody is unsure how to install check out [this Stackoverflow article](https://stackoverflow.com/questions/31553376/eclipse-how-to-install-a-plugin-manually).
