### ISSUE TITLE
Having difficulties to set up MoreUnit for development

### ISSUE THREAD

**Issue by rherrmann** [MoreUnit/MoreUnit-Eclipse#7]
After cloning the MoreUnit repository it took me some time to get the development environment set up so that the code compiled and the tests could be run.

What I think would help here is PDE target platform definition files, one for each supported version of Eclipse and instructions as where to find the master pom file (or move it to the root of the repository). A launch configuration to run all tests would also help.

**Comment by gianasista** [comment]
You are absolutely right, we should fix this. Many thanks for your pull request.

**Comment by rherrmann** [comment]
Fixed with pull request #9
