### ISSUE TITLE
Unable to install from zip file with eclipse 2018-12 (4.10)

### ISSUE THREAD

**Issue by ChristianLutz** [MoreUnit/MoreUnit-Eclipse#76]
I just downloaded the zip (3.2.0) file and tried to install the archive. This doesn't work anymore.
It doesn't show any content at all in the dialog.

**Comment by apupier** [comment]
I reproduce with 3.1.1 and 3.0.1, seems to be an old issue with tagged zip

**Comment by apupier** [comment]
I updated the latest release:
https://github.com/MoreUnit/MoreUnit-Eclipse/releases/tag/v3.2.0
![image](https://user-images.githubusercontent.com/1105127/51897444-087a6a00-23af-11e9-902e-0c9a2ff722d9.png)
I won't do it for previous version as nobody reported it.

**Comment by apupier** [comment]
@ChristianLutz thanks for having reported the issue. I updated the instructions for a release so it should be fine for the following ones.

**Comment by ChristianLutz** [comment]
Your welcome, thx for this helpful plugin.
