### ISSUE TITLE
Eclipse 4.11.0: MoreUnit plugin is not available

### ISSUE THREAD

**Issue by srssrs** [MoreUnit/MoreUnit-Eclipse#78]
I have tried to install MoreUnit plugin to Eclipse 4.11 but it doesn't appear on MarketPlace plugin
<img width="692" alt="screenshot" src="https://user-images.githubusercontent.com/6746414/54747873-5140e900-4bd0-11e9-9d56-8a0260d30b29.png">

**Comment by apupier** [comment]
seems now we have to manually add new releases as "compatible one".
I modified the marketplace entry for latest version:
![image](https://user-images.githubusercontent.com/1105127/54748108-04a9dd80-4bd1-11e9-9661-10f9c5870194.png)
it should be installable in latest Eclipse version.

thanks for the report

**Comment by srssrs** [comment]
Thank you! It works correctly
<img width="690" alt="screenshot" src="https://user-images.githubusercontent.com/6746414/54748699-a41ba000-4bd2-11e9-810f-5d3ed72c2dc9.png">
