### ISSUE TITLE
How do you install it?

### ISSUE THREAD

**Issue by mbarnett3** [MoreUnit/MoreUnit-Eclipse#79]

**Comment by helospark** [comment]
Have you tried it from the Eclipse Marketplace?
https://marketplace.eclipse.org/content/moreunit

**Comment by apupier** [comment]
there are 3 ways documented to install MoreUnit in Eclipse: https://moreunit.github.io/MoreUnit-Eclipse/#doc-install

(it includes the one that @helospark has pointed which is surely the easiest one)

I'm closing this issue. please open a more specific one if you encounter problems.
