### ISSUE TITLE
Template for generated test method

### ISSUE THREAD

**Issue by almondtools** [MoreUnit/MoreUnit-Eclipse#82]
MoreUnits generated test methods are limited to the pattern `public void testXXX() throws Exception`.

It could be an idea to use the templates already managed in eclipse to configure MoreUnit Ouput for methods. This would not only help teams with other naming conventions but also those who want to keep their tests package private (JUnit5 allows it).

**Comment by PyvesB** [comment]
Agreed, this would be a nice feature!
