### ISSUE TITLE
Make generated test class and test cases package-scoped in JUnit 5 tests

### ISSUE THREAD

**Issue by redcatbear** [MoreUnit/MoreUnit-Eclipse#85]
## Situation

When using `CTRL`+`u` to create a class or `CTRL`+`J` to create a test case in a JUnit 5 test, both generated sources are scoped `public`. In JUnit 5 tests the scope should be package though.

## Environment

Eclipse IDE for Java Developers
Version: 2020-03 (4.15.0)
Build id: 20200313-1211
OS: Linux, v.5.3.0-51-generic, x86_64 / gtk 3.24.12, WebKit 2.28.2
Java version: 13
MoreUnit for Java 3.2.1 (installed via Marketplace)

## Requested Change

1. Remove `public` modifier from test class in generated JUnit 5 test
1. Remove `public` modifier from test case in generated JUnit 5 test

**Comment by apupier** [comment]
quick code analysis just by reading it. It sounds like it is based on Eclipse JUnit support (and so would mean that it needs to be changed upstream): https://github.com/MoreUnit/MoreUnit-Eclipse/blob/cbe19341dbc3022e28ec055e3b0e693b5274e663/org.moreunit.plugin/src/org/moreunit/wizards/NewTestCaseWizard.java#L111

**Comment by kaklakariada** [comment]
I just tested this with a vanilla "Eclipse IDE for Enterprise Java and Web Developers" 2021-06 (4.20.0) on MacOS.
The "New JUnit Test Case" dialog creates a test class without `public` modifiers as expected:

```java
package org.itsallcode.whiterabbit.jfxui;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class AppTest
{
    @BeforeEach
    void setUp() throws Exception
    {
    }

    @Test
    void testMain()
    {
        fail("Not yet implemented");
    }
}
```

Either this issue was fixed in Eclipse 2021-06 or this is a problem in MoreUnit.

**Comment by apupier** [comment]
@kaklakariada thanks for the exploration and the detailed report.

it is effectively in MoreUnit codebase. I'm preparing a Pull Request.
