### ISSUE TITLE
Can't install in Eclipse 2020-03

### ISSUE THREAD

**Issue by quinao** [MoreUnit/MoreUnit-Eclipse#90]
Hello,

I've been using More Unit for some time and I really enjoy it, thank you!

However, I can't install it in Eclipse 2020-03. 
I don't find it in Eclipse Marketplace : searching for "moreunit" yields no results.
If I drag and drop it from [this webpage](https://marketplace.eclipse.org/user/vhenneberger/listings) into Eclipse, I get following error message: "The following solutions are not compatible with this version of Eclipse: MoreUnit".

I'm using Eclipse IDE for Enterprise Java Developers, version 2020-03 (4.15.0), on Debian 9.

-> Is it possible to use MoreUnit in Eclipse 2020-03, and if yes, how may I install it?

Thank you

**Comment by apupier** [comment]
I updated the entry on the marketplace. You should be able to install it now.

Please let me know if installation is working fine.

**Comment by quinao** [comment]
Thank you for the quick answer!
Unfortunatly it stil doesn't work - I get the same error message.

**Comment by apupier** [comment]
I tried with 2020-03 (4.15.0) by Drag'n'dropping from the Eclipse marketplace as you linked. It is working fine.
Wondering if there is not a cache for the request to install on marketplace client side.
Can you try to close the IDE and retry to install please?

**Comment by quinao** [comment]
Restarting Eclipse wasn't enough, but rebooting my laptop did.
It works fine now, thanks!

**Comment by apupier** [comment]
great, thanks for your report and for your patience
