### ISSUE TITLE
"Jump to test" as a code mining

### ISSUE THREAD

**Issue by MahatmaFatalError** [MoreUnit/MoreUnit-Eclipse#94]
Code minings are quite handy. It would be great if MoreUnit could contribute a way to have a code mining annotation on classes to jump to its corresponding test class.

**Comment by MahatmaFatalError** [comment]
Hi @RoiSoleil is that feature implemented?

**Comment by RoiSoleil** [comment]
No i was doing some clean up on Issues. I am reopong it.

**Comment by RoiSoleil** [comment]
@MahatmaFatalError would you like to test the new feature ? You have to enable it before :

![image](https://github.com/MoreUnit/MoreUnit-Eclipse/assets/3462260/637dd0fd-ef46-492a-addd-0f9150c2b551)

**Comment by MahatmaFatalError** [comment]
Awesome, thank you! Is there already a release published which I can install?

**Comment by RoiSoleil** [comment]
You can try the snapshot update site here : https://github.com/MoreUnit/MoreUnit-Eclipse/releases/download/snapshot/
