### ISSUE TITLE
Ctrl + J shortcut: Fails to jump back to test module (for C)

### ISSUE THREAD

**Issue by geoffdudds** [MoreUnit/MoreUnit-Eclipse#95]
I just started using this plugin to help try TDD in embedded C with Ceedling.

If I have the TextXXXX.c selected, ctrl+j jumps to XXXX.c.
If I have XXXX.c selected, ctrl+j produces this error:
![image](https://user-images.githubusercontent.com/69219109/101673204-ba533a80-3a0b-11eb-876f-17bbbbe0b181.png)

Like I said, I'm primarily using for C, but I have the java option installed too - not sure if that's causing a conflict?

Also, here is the outline of the folder structure (the relevant parts)
- Library
  - .cproject
  - .project
  - StdLib
    - source
      - *.c
    - test
      - test*.c

**Comment by apupier** [comment]
Would it be possible that the preferences is configured with a majuscule I and locally there is a miniscule one for StdLib/ StdLIb folder?

On Windows, by default, the folder names are case insensitive but maybe it refuses to create one with a different case?

**Comment by geoffdudds** [comment]
I'm sorry, I eventually got this figured out and forgot to come back and clean up my post.

I recall that it was a configuration error on my part but it was long enough ago I can't recall the details. I think it may have been an error in my regex expressions for source and test path. 

Apologies for leaving this hanging and not being able to provide the details necessary to help others who have similar issues.

The s/w works great - I have been using for a year now - very convenient!

**Comment by apupier** [comment]
no problem. i didn't had time to have a look before anyway.

Happy that the software is working great for you :-)
